[project]
name = "tallyhoe"
version = "0.4.2"
description = "Tally values in a CSV column."
requires-python = ">=3.11"
dependencies = []

[project.scripts]
tally = "tallyhoe.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tallyhoe"]
